-- 가스링크 보정기 관련 데이터 누락 데이터 수정

SELECT AFTER_MTR_NEW_FIX_FLAG -- '10'
     , COMPENS_FEE_FREE_FLAG -- 'N'
     , COMPENS_REPL_WHY -- '10'
     , VISIT_YMD -- '20260119'
     , A.*
FROM    C31.C3BT_MTR_REPL_TREAT  A
WHERE   REPL_TREAT_YMD  >= '20251001'
-- and mtr_num = '302198392'
AND     PDA_REPL_JOB_ITEM IN ('20','30')

AND     TRIM(AFTER_COMPENS_ID_NUM) IS NOT NULL
AND     TRIM(MTR_REPL_WHY) IS NOT NULL
AND     EXISTS(
    SELECT  *
    FROM     C31.C3BT_COMPENS_REPL_DD_RSLT X
    WHERE   X.MTR_NUM = A.MTR_NUM
    AND     X.REPL_TREAT_YMD = A.REPL_TREAT_YMD
    )
ORDER BY CRT_IP DESC
    ;