-- 자율안전점검 대상 여부
select B.CENTER_CD,
B.ZONE_MANAGE_NUM,
B.CHK_YEAR,
a.*
from C31.C3CT_GENER_SELF_CHK_OBJ A
, C31.C3CT_GENER_OBJ_PDA      B  -- 일반점검대상
, C31.C3AT_MTR C
where TO_CHAR(SYSDATE, 'YYYYMMDD') NOT BETWEEN A.SELF_CHK_STR AND A.SELF_CHK_END
AND A.CHK_EXEC_NUM = B.CHK_EXEC_NUM
AND A.MTR_NUM = C.MTR_NUM
AND B.CHK_YEAR = '2026'
            -- AND B.CHK_ORDER = #{chkOrder}