-- 자율안전점검 이번달 

SELECT B.CHK_YEAR
     , B.CHK_ORDER
     , B.CENTER_CD
     , B.ZONE_MANAGE_NUM
      , C.MTR_LOC_FLAG    -- 계량기 설치장소 (10:내부, 20:외부 등)
     , COUNT(*) AS CNT  -- 대상 건수
  FROM C31.C3CT_GENER_SELF_CHK_OBJ A  -- 자율안전점검대상
  INNER JOIN C31.C3CT_GENER_OBJ_PDA B -- 일반점검대상
    ON A.CHK_EXEC_NUM = B.CHK_EXEC_NUM
    INNER JOIN C31.C3AT_MTR C           -- 계량기 마스터
     ON A.MTR_NUM = C.MTR_NUM
 WHERE TO_CHAR(SYSDATE, 'YYYYMMDD') BETWEEN A.SELF_CHK_STR AND A.SELF_CHK_END
 GROUP BY B.CHK_YEAR, B.CHK_ORDER, B.CENTER_CD, B.ZONE_MANAGE_NUM, C.MTR_LOC_FLAG
 ORDER BY CNT DESC;