우선점검 생성

SELECT *
  FROM C31.C3CT_GENER_OBJ_PDA
 WHERE 1=1
   AND CHK_YEAR = '2026'
   AND CHK_ORDER = '10'
   AND CHK_TYPE = '11'
   AND CENTER_CD = '11'
   AND ZONE_MANAGE_NUM = '00650'
   AND TRIM(SEND_YN) IS NULL 
   AND (LENGTH(TRIM(PREUSE_CHK_WHY)) > 0 OR LENGTH(TRIM(RESERVED_DATE)) > 0)
   AND ROWNUM < 501
;

SELECT *
  FROM C31.C3CT_GENER_MTR_PDA
 WHERE CHK_EXEC_NUM IN (
SELECT CHK_EXEC_NUM
  FROM C31.C3CT_GENER_OBJ_PDA
 WHERE 1=1
   AND CHK_YEAR = '2026'
   AND CHK_ORDER = '10'
   AND CHK_TYPE = '11'
   AND ZONE_MANAGE_NUM = '00650'
   AND (LENGTH(TRIM(PREUSE_CHK_WHY)) > 0 OR LENGTH(TRIM(RESERVED_DATE)) > 0)
   AND TRIM(SEND_YN) IS NULL 
   AND ROWNUM < 501)
;